SELECT 
    P.IDPRODUTO, 
    P.DESCRICAO_PRODUTO, 
    COALESCE(P.PRECO_VENDA, 0) AS PRECO_VENDA, 
    COALESCE(P.IDSUBGRUPO_PRODUTO, 0) AS IDSUBGRUPO_PRODUTO,
    COALESCE(P.PRECO_PROMOCIONAL, 0) AS PRECO_PROMOCIONAL,
    COALESCE(P.DATA_LIMITE_PROM, '0') AS DATA_LIMITE_PROM,
    COALESCE(P.DATA_INICIO_PROM, '0') AS DATA_INICIO_PROM,
    COALESCE(P.CODIGO_BARRA, '0') AS CODIGO_BARRA
FROM 
    PRODUTOS P
JOIN 
    ESTOQUES E ON P.IDPRODUTO = E.IDPRODUTO
WHERE 
    P.SITUACAO_PRODUTO = 'AB'
    AND P.IDSUBGRUPO_PRODUTO <> 6000001
ORDER BY 
    P.DESCRICAO_PRODUTO;
